services:
  - type: web
    name: k-pos-be
    env: docker
    region: singapore
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        sync: false
      - key: API_PREFIX
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
